load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#
# Rules Kotlin
# https://github.com/bazelbuild/rules_kotlin
#

rules_kotlin_version = "v1.5.0-alpha-3"
rules_kotlin_sha = "eeae65f973b70896e474c57aa7681e444d7a5446d9ec0a59bb88c59fc263ff62"
http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/%s/rules_kotlin_release.tgz" % rules_kotlin_version],
    sha256 = rules_kotlin_sha,
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
register_toolchains("//:kotlin_toolchain")

#
# JVM External
# https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.0
#

RULES_JVM_EXTERNAL_TAG = "4.0"
RULES_JVM_EXTERNAL_SHA = "31701ad93dbfe544d597dbe62c9a1fdd76d81d8a9150c2bf1ecf928ecdf97169"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

# https://github.com/ajalt/clikt/
maven_install(
    artifacts = [
        "org.apache.httpcomponents:httpcomponents-client:4.5.13",
        "commons-httpclient:commons-httpclient:3.1",
        "org.apache.httpcomponents:httpcore:4.4.6",
        "org.apache.httpcomponents:httpclient:4.5.3",
        "commons-io:commons-io:2.4",
        "commons-lang:commons-lang:2.6",
        "org.codehaus.groovy:groovy-all:2.4.6",
        "net.sf.ezmorph:ezmorph:1.0.6",
        "org.kohsuke.stapler:json-lib:2.4-jenkins-3",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
        "https://repo.jenkins-ci.org/public/",
    ],
)
